# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: api.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'api.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.api import annotations_pb2 as google_dot_api_dot_annotations__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\tapi.proto\x12\x03\x61pi\x1a\x1cgoogle/api/annotations.proto\"\x19\n\x0bUserRequest\x12\n\n\x02id\x18\x01 \x01(\x05\")\n\x0cUserResponse\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0b\n\x03\x61ge\x18\x02 \x01(\x05\x32T\n\nApiService\x12\x46\n\x07GetUser\x12\x10.api.UserRequest\x1a\x11.api.UserResponse\"\x16\x82\xd3\xe4\x93\x02\x10\x12\x0e/api/user/{id}B!Z\x1fgithub.com/wayanputri/backendPYb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'api_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\037github.com/wayanputri/backendPY'
  _globals['_APISERVICE'].methods_by_name['GetUser']._loaded_options = None
  _globals['_APISERVICE'].methods_by_name['GetUser']._serialized_options = b'\202\323\344\223\002\020\022\016/api/user/{id}'
  _globals['_USERREQUEST']._serialized_start=48
  _globals['_USERREQUEST']._serialized_end=73
  _globals['_USERRESPONSE']._serialized_start=75
  _globals['_USERRESPONSE']._serialized_end=116
  _globals['_APISERVICE']._serialized_start=118
  _globals['_APISERVICE']._serialized_end=202
# @@protoc_insertion_point(module_scope)
